### ISSUE TITLE
Change hardcoded currency

### ISSUE THREAD

**Issue by bjarnef** [warrenbuckley/Analytics#11]
Consider how to seet which currency that should be used. In Google Analytics there is a setting "currency shown as", which I think you can get through the API.

![2014-10-01_23-18-31](https://cloud.githubusercontent.com/assets/2919859/4483380/f04b77da-49b0-11e4-9a08-f3114c0efbab.jpg)

Or perhaps a dropdown in the package settings view with a dropdown with the same currencies. I am not sure how the it will affect the price - in my example I use ecommerce data from a webshop, where the currency is send to Google Analytics in DKK.

**Comment by warrenbuckley** [comment]
@bjarnef & @abjerner any news/updates on this guys?

**Comment by bjarnef** [comment]
@warrenbuckley I had submitted a PR so it just use the currency set as default in your GA profile, but later it maybe should be possible to change it from settings.

**Comment by warrenbuckley** [comment]
OK looks like I can close this then @bjarnef, as I merged in your PR this morning here
https://github.com/warrenbuckley/Analytics/pull/14

**Comment by abjerner** [comment]
Regarding later being able to change the currency, I don't think that is possible. As far as I know, The API will just return the currency as specified in Google Analytics. But then again, I haven't worked much with currencies in Analytics.

It is of course possible to do some conversion after the data has been fetched from the API, but requires another service for looking up the exchange rates.

**Comment by bjarnef** [comment]
Yes, for now you can just switch the currency for your Google Analytics profile, but I was also thinking that some editors might use different language and prefer different currencies. I am not sure how Google Analytics handle the conversion e.g. when I have a webshop with prices in DKK and Google Analytics track the orders and I then i Google Analytics can change the currency and e.g. see prices in USD. They probably use a service for the exchange rates - maybe Google has its own service for that - but it have to be up-to-date with latest exchange rates.

**Comment by bjarnef** [comment]
This one seems to be popular https://openexchangerates.org/showcase

But I think some free services / open source code could be used.
https://github.com/petebacondarwin/angular-exchange-rates
