### ISSUE TITLE
Google.Apis.Auth.Mvc4.dll causing error for Grid feature in Umbraco 7.2.*

### ISSUE THREAD

**Issue by stephendougherty** [warrenbuckley/Analytics#15]
Hi Guys,

I'll refer to this thread

http://our.umbraco.org/forum/umbraco-7/using-umbraco-7/59567-Umbraco-72-error-at-GetGridHtml?p=0#comment204075

to bring to your attention an issue I noticed when the Google.Apis.Auth.Mvc4.dll is in the bin directory for my site. I read somewhere that you guys are not even using this anymore. Perhaps you have more knowledge on what's going on here.

Anyway I thought I would make you aware of this.

Regards,
Stephen

**Comment by abjerner** [comment]
Yes, the Google DLLs are not used, and was removed in this https://github.com/warrenbuckley/Analytics/commit/afbe3ef3cb4b89ad99aaab88fdf0c15e28ca281d about a year ago. If you don't use the DLLs for anything else, you can simply delete them from the bin folder.

@warrenbuckley Can we publish a new package without the Google DLLs?

**Comment by warrenbuckley** [comment]
@stephendougherty have you tried manually removing the DLL in question for the time being. Did that resolve it or did it blow up the site?

**Comment by stephendougherty** [comment]
Hi Warren,
Yes removing it fixed this issue thanks.
RegardsStephen





On Tue, Feb 17, 2015 at 8:10 AM -0800, "Warren Buckley" <notifications@github.com> wrote:
@stephendougherty have you tried manually removing the DLL in question for the time being. Did that resolve it or did it blow up the site?

---
