### ISSUE TITLE
Add track by on ng-repeat to optimize performance

### ISSUE THREAD

**Issue by bjarnef** [warrenbuckley/Analytics#19]
Can we add track by in the end of ng-repeat? that will optimize the performance - it just needs to use an unique key:
http://www.codelord.net/2014/04/15/improving-ng-repeat-performance-with-track-by/

there is a built in $id() function that can be used to assign an unique $$hashKey behind the scenes if there isn't a unique id in the properties: https://docs.angularjs.org/api/ng/directive/ngRepeat

**Comment by warrenbuckley** [comment]
I have closed this due to the pull request https://github.com/warrenbuckley/Analytics/pull/21
