### ISSUE TITLE
Umbraco Analytics not working with Umbraco 7

### ISSUE THREAD

**Issue by amfh** [warrenbuckley/Analytics#55]
Hi
Analytics section is missing in backoffice after installing Analytics on Umbraco 7.7.8 or 7.7.7. No errors on browser console or log files.
Is Analytics not compatible with latest version of Umbraco?

Br
Ali

**Comment by abjerner** [comment]
@amfh If I remember correctly, you need to grant your user (or user group) access to the new *Analytics* section. It won't show up by default.

**Comment by amfh** [comment]
You are right. Thank you ver much.
