### ISSUE TITLE
Binary Error when trying to install package on Umbraco 7.1.4

### ISSUE THREAD

**Issue by Jeffri** [warrenbuckley/Analytics#7]
Error report
This package could not be verified for compatibility. An error occurred while loading a referenced assembly 'Newtonsoft.Json' see error log for full details.
This package could not be verified for compatibility. An error occurred while loading a referenced assembly 'Newtonsoft.Json' see error log for full details.
This package references the assembly 'System.Threading.Tasks' which was not found
This package could not be verified for compatibility. An error occurred while loading a referenced assembly 'System.Net.Http' see error log for full details.
This package references the assembly 'System' which was not found
This package references the assembly 'System.Core' which was not found
This package could not be verified for compatibility. An error occurred while loading a referenced assembly 'Newtonsoft.Json' see error log for full details.
This package references the assembly 'System.Runtime' which was not found
This package references the assembly 'System.Net' which was not found
This package references the assembly 'System.Threading.Tasks' which was not found
This package references the assembly 'System.Runtime' which was not found
This package could not be verified for compatibility. An error occurred while loading a referenced assembly 'System.Net.Http' see error log for full details.
This package references the assembly 'System.Threading.Tasks' which was not found
This package references the assembly 'System.Runtime' which was not found
This package references the assembly 'System' which was not found
This package references the assembly 'Microsoft.Threading.Tasks.Extensions.Desktop' which was not found
This package could not be verified for compatibility. An error occurred while loading a referenced assembly 'System.Net.Http' see error log for full details.
This package could not be verified for compatibility. An error occurred while loading a referenced assembly 'System.Net.Http' see error log for full details.
This package references the assembly 'System.Threading.Tasks' which was not found
This package references the assembly 'System.Net' which was not found
This package references the assembly 'System.Core' which was not found
This package could not be verified for compatibility. An error occurred while loading a referenced assembly 'Newtonsoft.Json' see error log for full details.
This package references the assembly 'System' which was not found
This package references the assembly 'System.Runtime' which was not found
This package could not be verified for compatibility. An error occurred while loading a referenced assembly 'System.Net.Http.Primitives' see error log for full details.
This package could not be verified for compatibility. An error occurred while loading a referenced assembly 'log4net' see error log for full details.
This package references the assembly 'System' which was not found

**Comment by warrenbuckley** [comment]
Closed due to message in Forum thread above...
