### ISSUE TITLE
Change of date range not completely update chart

### ISSUE THREAD

**Issue by bjarnef** [warrenbuckley/Analytics#9]
When you change the date range, it does update the chart. However with the new interactive features in the new version of Chart.js, it seems to keep the old version of the chart when hovering the chart.

I think we somehow need to update/refresh/redraw the chart after the date range has been changed.

**Comment by warrenbuckley** [comment]
Is this resolved now @bjarnef due to your commit for this?

**Comment by bjarnef** [comment]
Yes it should be.. It worked when I tested It at that time :)

**Comment by warrenbuckley** [comment]
Will close this then @bjarnef
